# Translations template for nova_powervm.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 3.0.0.0rc2.dev5\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-09-28 06:17-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: nova_powervm/virt/powervm/driver.py:634
#, python-format
msgid ""
"Removing %(num_maps)d storage-less VSCSI mappings associated with LPAR ID"
" %(lpar_uuid)s from VIOS %(vios_name)s."
msgstr ""

#: nova_powervm/virt/powervm/driver.py:674
#: nova_powervm/virt/powervm/driver.py:684
msgid "VM was not found during destroy operation."
msgstr ""

#: nova_powervm/virt/powervm/driver.py:1082
msgid "VM was not found during unplug operation as it is already possibly deleted"
msgstr ""

#: nova_powervm/virt/powervm/driver.py:1109
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: "
"%(ifaces)s"
msgstr ""

#: nova_powervm/virt/powervm/driver.py:1588
msgid "Rolling back live migration."
msgstr ""

#: nova_powervm/virt/powervm/driver.py:2042
#, python-format
msgid "Unable to parse event URI: %s from PowerVM."
msgstr ""

#: nova_powervm/virt/powervm/host.py:207
#, python-format
msgid ""
"Host CPU Metrics determined that the total cycles reported was less than "
"the used cycles.  This indicates an issue with the PCM data.  Please "
"investigate the results.\n"
"Total Delta Cycles: %(tot_cycles)d\n"
"User Delta Cycles: %(user_cycles)d\n"
"Firmware Delta Cycles: %(fw_cycles)d"
msgstr ""

#: nova_powervm/virt/powervm/slot.py:180
#, python-format
msgid ""
"Unable to delete the slot map from Swift backing store with ID %(key)s.  "
"Will require manual cleanup."
msgstr ""

#: nova_powervm/virt/powervm/vif.py:263 nova_powervm/virt/powervm/vif.py:459
#: nova_powervm/virt/powervm/vif.py:609
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  The VIF was"
" not found on the instance."
msgstr ""

#: nova_powervm/virt/powervm/vif.py:474
#, python-format
msgid ""
"Unable to delete device %(dev_name)s from bridge %(bridge)s. Error: "
"%(error)s"
msgstr ""

#: nova_powervm/virt/powervm/vif.py:535
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  No matching"
" vNIC was found on the instance.  VIF: %(vif)s"
msgstr ""

#: nova_powervm/virt/powervm/disk/driver.py:199
#, python-format
msgid ""
"Failed to map boot disk %(disk_name)s of instance %(instance_name)s to "
"the management partition from Virtual I/O Server %(vios_name)s: %(exc)s"
msgstr ""

#: nova_powervm/virt/powervm/nvram/manager.py:127
#, python-format
msgid "Could not delete NVRAM: %s"
msgstr ""

#: nova_powervm/virt/powervm/nvram/manager.py:198
#, python-format
msgid "Unable to store the NVRAM for instance: %s"
msgstr ""

#: nova_powervm/virt/powervm/nvram/swift.py:285
#, python-format
msgid "Could not remove temporary file: %s"
msgstr ""

#: nova_powervm/virt/powervm/tasks/base.py:63
#, python-format
msgid "Reverting task %(task)s for instance %(inst)s"
msgstr ""

#: nova_powervm/virt/powervm/tasks/base.py:71
#, python-format
msgid ""
"Revert task %(task)s completed in %(seconds)d seconds for instance "
"%(inst)s"
msgstr ""

#: nova_powervm/virt/powervm/tasks/network.py:177
#, python-format
msgid "Instance was not assigned to this host. It was assigned to: %s"
msgstr ""

#: nova_powervm/virt/powervm/tasks/network.py:259
#, python-format
msgid "VIF creation being rolled back for instance %(inst)s"
msgstr ""

#: nova_powervm/virt/powervm/tasks/network.py:271
msgid "An exception occurred during an unplug in the vif rollback.  Ignoring."
msgstr ""

#: nova_powervm/virt/powervm/tasks/storage.py:60
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be disconnected"
msgstr ""

#: nova_powervm/virt/powervm/tasks/storage.py:76
#, python-format
msgid ""
"Unable to disconnect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""

#: nova_powervm/virt/powervm/tasks/storage.py:108
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be re-connected"
msgstr ""

#: nova_powervm/virt/powervm/tasks/storage.py:125
#, python-format
msgid ""
"Unable to re-connect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""

#: nova_powervm/virt/powervm/tasks/storage.py:274
#, python-format
msgid ""
"Unmapping boot disk %(disk_name)s of instance %(instance_name)s from "
"management partition via Virtual I/O Server %(vios_name)s."
msgstr ""

#: nova_powervm/virt/powervm/tasks/storage.py:286
#, python-format
msgid "Removing disk %(disk_path)s from the management partition."
msgstr ""

#: nova_powervm/virt/powervm/tasks/storage.py:527
#, python-format
msgid "Disk not found: %(disk_name)s"
msgstr ""

#: nova_powervm/virt/powervm/tasks/vm.py:226
#, python-format
msgid "Powering off instance: %s"
msgstr ""

#: nova_powervm/virt/powervm/volume/iscsi.py:163
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual "
"I/O Server %(vios)s is not in a valid state.  No disconnect actions to be"
" taken as volume is not healthy."
msgstr ""

#: nova_powervm/virt/powervm/volume/iscsi.py:172
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server "
"%(vios_name)s for volume %(volume_id)s. Error: %(error)s"
msgstr ""

#: nova_powervm/virt/powervm/volume/iscsi.py:214
#: nova_powervm/virt/powervm/volume/vscsi.py:327
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the volume %(volume_id)s on ANY "
"of the Virtual I/O Servers for instance %(inst)s."
msgstr ""

#: nova_powervm/virt/powervm/volume/npiv.py:488
#, python-format
msgid ""
"Had to update the system metadata for the WWPNs due to incorrect physical"
" WWPNs on fabric %(fabric)s"
msgstr ""

#: nova_powervm/virt/powervm/volume/npiv.py:587
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC "
"Fabric %(fabric)s."
msgstr ""

#: nova_powervm/virt/powervm/volume/npiv.py:705
#, python-format
msgid ""
"No NPIV mappings exist for instance %(inst)s on fabric %(fabric)s.  May "
"not have connected to the fabric yet or fabric configuration was recently"
" modified."
msgstr ""

#: nova_powervm/virt/powervm/volume/volume.py:242
#, python-format
msgid ""
"There was an error removing the hdisk %(disk)s from the Virtual I/O "
"Server."
msgstr ""

#: nova_powervm/virt/powervm/volume/volume.py:281
#, python-format
msgid "Could not remove hdisk for volume: %s"
msgstr ""

#: nova_powervm/virt/powervm/volume/vscsi.py:197
#, python-format
msgid ""
"Discovered device %(dev)s for volume %(volume)s on %(vios)s is in use. "
"Error code: %(status)s."
msgstr ""

#: nova_powervm/virt/powervm/volume/vscsi.py:277
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual "
"I/O Server %(vios)s is not in a valid state.  This may be the result of "
"an evacuate."
msgstr ""

#: nova_powervm/virt/powervm/volume/vscsi.py:286
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server "
"%(vios_name)s for volume %(volume_id)s. Volume UDID: %(volume_uid)s.  "
"Error: %(error)s"
msgstr ""

