# Translations template for nova_powervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 4.0.1.dev5\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:07-0400\n"
"PO-Revision-Date: 2017-04-20 10:07-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: nova_powervm/virt/powervm/driver.py:624
#, python-format
msgid ""
"Removing %(num_maps)d storage-less VSCSI mappings associated with LPAR ID "
"%(lpar_uuid)s from VIOS %(vios_name)s."
msgstr ""
"Retrait de %(num_maps)d mappages VSCSI sans stockage associés à l'ID LPAR "
"%(lpar_uuid)s depuis le VIOS %(vios_name)s."

#: nova_powervm/virt/powervm/driver.py:664
#: nova_powervm/virt/powervm/driver.py:674
msgid "VM was not found during destroy operation."
msgstr "Machine virtuelle introuvable lors de l'opération de destruction."

#: nova_powervm/virt/powervm/driver.py:1075
msgid ""
"VM was not found during unplug operation as it is already possibly deleted"
msgstr ""
"Machine virtuelle introuvable lors de l'opération de débranchement car elle a peut-être déjà été supprimée."

#: nova_powervm/virt/powervm/driver.py:1102
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: %(ifaces)s"
msgstr ""
"Adresse my_ip (%(my_ip)s) introuvable sur aucune des interfaces : %(ifaces)s"

#: nova_powervm/virt/powervm/driver.py:1571
msgid "Rolling back live migration."
msgstr "Annulation de la migration active."

#: nova_powervm/virt/powervm/event.py:121
#, python-format
msgid "Unable to parse event URI: %s from PowerVM."
msgstr "Impossible d'analyser l'URI d'événement %s depuis PowerVM."

#: nova_powervm/virt/powervm/host.py:204
#, python-format
msgid ""
"Host CPU Metrics determined that the total cycles reported was less than the "
"used cycles.  This indicates an issue with the PCM data.  Please investigate "
"the results.\n"
"Total Delta Cycles: %(tot_cycles)d\n"
"User Delta Cycles: %(user_cycles)d\n"
"Firmware Delta Cycles: %(fw_cycles)d"
msgstr ""
"Selon les mesures d'UC hôte, le nbre total de cycles consignés est inférieur "
"aux cycles utilisés.  Ceci indique un problème de données PCM.  Examinez "
"les résultats .\n"
"Total des cycles delta : %(tot_cycles)d\n"
"Cycles delta de l'utilisateur : %(user_cycles)d\n"
"Cycles delta du microprogramme : %(fw_cycles)d"

#: nova_powervm/virt/powervm/slot.py:180
#, python-format
msgid ""
"Unable to delete the slot map from Swift backing store with ID %(key)s.  "
"Will require manual cleanup."
msgstr ""
"Impossible de supprimer la carte d'emplacements depuis magasin support  "
"Swift avec ID %(key)s. Nettoyage manuel requis."

#: nova_powervm/virt/powervm/vif.py:357 nova_powervm/virt/powervm/vif.py:588
#: nova_powervm/virt/powervm/vif.py:758
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  The VIF was "
"not found on the instance."
msgstr ""
"Impossible de débrancher le VIF avec l'adresse mac %(mac)s pour l'instance "
"%(inst)s. VIF introuvable sur l'instance."

#: nova_powervm/virt/powervm/vif.py:604
#, python-format
msgid ""
"Unable to delete device %(dev_name)s from bridge %(bridge)s. Error: %(error)s"
msgstr ""
"Impossible supprimer unité %(dev_name)s du pont %(bridge)s. Erreur : %(error)s"

#: nova_powervm/virt/powervm/vif.py:685
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  No matching "
"vNIC was found on the instance.  VIF: %(vif)s"
msgstr ""
"Impossible de débrancher le VIF avec l'adresse mac %(mac)s pour l'instance "
"%(inst)s. Aucun vNIC correspondant détecté sur l'instance.  VIF : %(vif)s"

#: nova_powervm/virt/powervm/vif.py:827
#, python-format
msgid "Rolling back the live migrate of VIF with mac %(mac)s."
msgstr "Annulation de la migration active du VIF avec l'adresse MAC %(mac)s."

#: nova_powervm/virt/powervm/vif.py:857
#, python-format
msgid "Deleting target side trunk adapter %(dev)s for rollback operation"
msgstr "Suppression de la carte de ligne réseau côté cible %(dev)s pour l'opération d'annulation"

#: nova_powervm/virt/powervm/disk/driver.py:225
#, python-format
msgid ""
"Failed to map boot disk %(disk_name)s of instance %(instance_name)s to the "
"management partition from Virtual I/O Server %(vios_name)s: %(exc)s"
msgstr ""
"Echec mappage disque d'amorçage %(disk_name)s de l'instance %(instance_name)s "
"à la partition de gestion du serveur VIOS %(vios_name)s: %(exc)s"

#: nova_powervm/virt/powervm/disk/driver.py:354
#, python-format
msgid ""
"Instance %(inst)s Disk Upload attempt #%(attempt)d failed. Retrying the "
"upload."
msgstr ""
"Instance %(inst)s Echec de tentative de chargement de disque n° %(attempt)d. "
"Nouvelle tentative."

#: nova_powervm/virt/powervm/nvram/manager.py:127
#, python-format
msgid "Could not delete NVRAM: %s"
msgstr "Impossible de supprimer la mémoire rémanente : %s"

#: nova_powervm/virt/powervm/nvram/manager.py:198
#, python-format
msgid "Unable to store the NVRAM for instance: %s"
msgstr "Impossible de stocker la mémoire rémanente (NVRAM) pour l'instance %s"

#: nova_powervm/virt/powervm/nvram/swift.py:182
msgid "NVRAM upload failed due to invalid token. Retrying upload."
msgstr "Echec téléchargement de la mémoire rémanente en raison d'un jeton non valide. Nouvelle tentative."

#: nova_powervm/virt/powervm/nvram/swift.py:288
#, python-format
msgid "Could not remove temporary file: %s"
msgstr "Impossible de retirer le fichier temporaire %s"

#: nova_powervm/virt/powervm/tasks/base.py:63
#, python-format
msgid "Reverting task %(task)s for instance %(inst)s"
msgstr "Rétablissement de la tâche %(task)s pour l'instance %(inst)s"

#: nova_powervm/virt/powervm/tasks/base.py:71
#, python-format
msgid ""
"Revert task %(task)s completed in %(seconds)d seconds for instance %(inst)s"
msgstr ""
"Rétablissement tâche %(task)s terminé en %(seconds)d s pour instance %(inst)s"

#: nova_powervm/virt/powervm/tasks/network.py:169
#, python-format
msgid "Instance was not assigned to this host. It was assigned to: %s"
msgstr "Instance non affectée à cet hôte. Affectée à : %s"

#: nova_powervm/virt/powervm/tasks/network.py:252
#, python-format
msgid "VIF creation being rolled back for instance %(inst)s"
msgstr "Création de VIF en cours d'annulation pour l'instance %(inst)s"

#: nova_powervm/virt/powervm/tasks/network.py:264
msgid "An exception occurred during an unplug in the vif rollback.  Ignoring."
msgstr "Exception lors d'une déconnexion dans l'annulation de VIF. Ignorer."

#: nova_powervm/virt/powervm/tasks/network.py:312
#, python-format
msgid ""
"No management VIF created for instance %s due to lack of Management Virtual "
"Switch"
msgstr ""
"Aucun VIF de gestion créé pour l'instance %s en raison de l'absence d'un "
"commutateur virtuel de gestion"

#: nova_powervm/virt/powervm/tasks/storage.py:62
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be disconnected"
msgstr "Volume %(vol)s pour l'instance %(inst)s à déconnecter"

#: nova_powervm/virt/powervm/tasks/storage.py:78
#, python-format
msgid ""
"Unable to disconnect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Déconnexion impossible du volume pour %(inst)s pendant l'annulation. Erreur : "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:110
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be re-connected"
msgstr "Volume %(vol)s pour l'instance %(inst)s à reconnecter"

#: nova_powervm/virt/powervm/tasks/storage.py:127
#, python-format
msgid ""
"Unable to re-connect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Reconnexion impossible du volume pour %(inst)s pendant l'annulation. Erreur : "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:284
#, python-format
msgid ""
"Unmapping boot disk %(disk_name)s of instance %(instance_name)s from "
"management partition via Virtual I/O Server %(vios_name)s."
msgstr ""
"Démappage du disque d'amorçage %(disk_name)s de l'instance %(instance_name)s "
"de la partition de gestion via le serveur Virtual I/O Server %(vios_name)s."

#: nova_powervm/virt/powervm/tasks/storage.py:296
#, python-format
msgid "Removing disk %(disk_path)s from the management partition."
msgstr "Retrait du disque %(disk_path)s de la partition de gestion."

#: nova_powervm/virt/powervm/tasks/storage.py:407
#, python-format
msgid "Vopt removal as part of spawn reversion failed with: %(exc)s"
msgstr "Echec du retrait de l'unité optique virtuelle dans le cadre de la réversion de génération avec %(exc)s"

#: nova_powervm/virt/powervm/tasks/storage.py:545
#, python-format
msgid "Disk not found: %(disk_name)s"
msgstr "Disque introuvable : %(disk_name)s"

#: nova_powervm/virt/powervm/tasks/vm.py:226
#, python-format
msgid "Powering off instance: %s"
msgstr "Désactivation de l'instance : %s"

#: nova_powervm/virt/powervm/volume/iscsi.py:153
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual I/O "
"Server %(vios)s is not in a valid state.  No disconnect actions to be taken "
"as volume is not healthy."
msgstr ""
"Déconnexion volume : hdisk de support pour volume %(volume_id)s sur serveur "
"VIOS %(vios)s pas dans un état valide.  Aucune action de déconnexion n'est "
"requise car le volume n'est pas sain."

#: nova_powervm/virt/powervm/volume/iscsi.py:163
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server %(vios_name)s "
"for volume %(volume_id)s. Error: %(error)s"
msgstr ""
"Déconnexion volume : Echec de détection de disque sur le serveur VIOS "
"%(vios_name)s pour le volume %(volume_id)s. Erreur : %(error)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:206
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the  volume %(volume_id)s on ANY of "
"the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Déconnexion volume : Echec de déconnexion du volume %(volume_id)s sur "
"l'un des serveurs Virtual I/O Server pour l'instance %(inst)s."

#: nova_powervm/virt/powervm/volume/npiv.py:490
#, python-format
msgid ""
"Had to update the system metadata for the WWPNs due to incorrect physical "
"WWPNs on fabric %(fabric)s"
msgstr ""
"Métadonnées système non mises à jour pour les WWPN car ceux-ci sont "
"incorrects sur l'ensemble de noeuds %(fabric)s"

#: nova_powervm/virt/powervm/volume/npiv.py:590
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC Fabric "
"%(fabric)s."
msgstr ""
"Aucune connexion de stockage détectée entre les serveurs Virtual I/O Server "
"%(fabric)s."

#: nova_powervm/virt/powervm/volume/npiv.py:703
#, python-format
msgid ""
"No NPIV mappings exist for instance %(inst)s on fabric %(fabric)s.  May not "
"have connected to the fabric yet or fabric configuration was recently "
"modified."
msgstr ""
"Aucun mappage NPIV existant pour l'instance %(inst)s sur l'ensemble de "
"noeuds %(fabric)s. L'ensemble n'est peut-être pas encore connecté ou la "
"configuration d'ensemble de noeuds a peut-être été modifiée récemment."

#: nova_powervm/virt/powervm/volume/volume.py:242
#, python-format
msgid ""
"There was an error removing the hdisk %(disk)s from the Virtual I/O Server."
msgstr ""
"Erreur lors du retrait du hdisk %(disk)s du serveur Virtual I/O Server."

#: nova_powervm/virt/powervm/volume/volume.py:282
#, python-format
msgid "Could not remove hdisk for volume: %s"
msgstr "Impossible de retirer le hdisk pour le volume %s"

#: nova_powervm/virt/powervm/volume/vscsi.py:197
#, python-format
msgid ""
"Discovered device %(dev)s for volume %(volume)s on %(vios)s is in use. Error "
"code: %(status)s."
msgstr ""
"Unité détectée %(dev)s pour le volume %(volume)s sur le serveur %(vios)s Erreur "
"d'état : %(status)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:278
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual I/O "
"Server %(vios)s is not in a valid state.  This may be the result of an "
"evacuate."
msgstr ""
"Déconnexion volume : hdisk de support pour volume %(volume_id)s sur serveur "
"VIOS %(vios)s pas dans un état valide.  Cela peut être le résultat d'une "
"évacuation."

#: nova_powervm/virt/powervm/volume/vscsi.py:288
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server %(vios_name)s "
"for volume %(volume_id)s. Volume UDID: %(volume_uid)s.  Error: %(error)s"
msgstr ""
"Déconnexion volume : Echec de détection de disque sur le serveur VIOS "
"%(vios_name)s pour le volume %(volume_id)s. UDID volume : %(volume_uid)s.  Erreur : %(error)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:330
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the volume %(volume_id)s on ANY of "
"the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Déconnexion volume : Echec de déconnexion du volume %(volume_id)s sur "
"l'un des serveurs Virtual I/O Server pour l'instance %(inst)s."

# ENGL1SH_VERS10N 12659_13 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 49
# T9N_SH1P_STR1NG PV133AAP001 2
