# Translations template for nova_powervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 4.0.1.dev5\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:07-0400\n"
"PO-Revision-Date: 2017-04-20 10:07-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: nova_powervm/virt/powervm/driver.py:624
#, python-format
msgid ""
"Removing %(num_maps)d storage-less VSCSI mappings associated with LPAR ID "
"%(lpar_uuid)s from VIOS %(vios_name)s."
msgstr ""
"Entfernen von %(num_maps)d speicherlosen Zuordnungen, die mit LPAR ID "
"%(lpar_uuid)s verbunden sind, vom virtuellen E/A-Server %(vios_name)s."

#: nova_powervm/virt/powervm/driver.py:664
#: nova_powervm/virt/powervm/driver.py:674
msgid "VM was not found during destroy operation."
msgstr "Die VM wurde während des Löschvorgangs nicht gefunden."

#: nova_powervm/virt/powervm/driver.py:1075
msgid ""
"VM was not found during unplug operation as it is already possibly deleted"
msgstr ""
"Die VM wurde während des Trennvorgangs nicht gefunden, da sie möglicherweise bereits gelöscht ist."

#: nova_powervm/virt/powervm/driver.py:1102
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: %(ifaces)s"
msgstr ""
"Die my_ip Adresse (%(my_ip)s) wurde auf keiner der folgenden Schnittstellen gefunden: %(ifaces)s"

#: nova_powervm/virt/powervm/driver.py:1571
msgid "Rolling back live migration."
msgstr "Ein Rollback der Livemigration wird durchgeführt."

#: nova_powervm/virt/powervm/event.py:121
#, python-format
msgid "Unable to parse event URI: %s from PowerVM."
msgstr "Ereignis-URI kann nicht ausgewertet werden: %s von PowerVM."

#: nova_powervm/virt/powervm/host.py:204
#, python-format
msgid ""
"Host CPU Metrics determined that the total cycles reported was less than the "
"used cycles.  This indicates an issue with the PCM data.  Please investigate "
"the results.\n"
"Total Delta Cycles: %(tot_cycles)d\n"
"User Delta Cycles: %(user_cycles)d\n"
"Firmware Delta Cycles: %(fw_cycles)d"
msgstr ""
"Anhand der Host-CPU-Metriken wurde festgestellt, dass die gemeldete Gesamtzahl Zyklen kleiner als "
"die Anzahl der verwendeten Zyklen war. Dies weist auf ein Problem mit den PCM-Daten hin. Die "
"Ergebnisse sollten überprüft werden.\n"
"Gesamtzahl Deltazyklen: %(tot_cycles)d\n"
"Benutzerdeltazyklen: %(user_cycles)d\n"
"Firmwaredeltazyklen: %(fw_cycles)d"

#: nova_powervm/virt/powervm/slot.py:180
#, python-format
msgid ""
"Unable to delete the slot map from Swift backing store with ID %(key)s.  "
"Will require manual cleanup."
msgstr ""
"Die Steckplatzzuordnung im Swift-Sicherungsspeicher mit ID %(key)s konnte nicht gelöscht werden. "
"Danach ist eine manuelle Bereinigung erforderlich."

#: nova_powervm/virt/powervm/vif.py:357 nova_powervm/virt/powervm/vif.py:588
#: nova_powervm/virt/powervm/vif.py:758
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  The VIF was "
"not found on the instance."
msgstr ""
"Der VIF mit MAC %(mac)s für Instanz %(inst)s konnte nicht getrennt werden. Der VIF wurde "
"nicht auf der Instanz gefunden."

#: nova_powervm/virt/powervm/vif.py:604
#, python-format
msgid ""
"Unable to delete device %(dev_name)s from bridge %(bridge)s. Error: %(error)s"
msgstr ""
"Die Einheit %(dev_name)s in Brücke %(bridge)s konnte nicht gelöscht werden. Fehler: %(error)s"

#: nova_powervm/virt/powervm/vif.py:685
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  No matching "
"vNIC was found on the instance.  VIF: %(vif)s"
msgstr ""
"Der VIF mit MAC %(mac)s für Instanz %(inst)s konnte nicht getrennt werden. Es "
"wurde kein passendes vNIC auf der Instanz gefunden. VIF: %(vif)s"

#: nova_powervm/virt/powervm/vif.py:827
#, python-format
msgid "Rolling back the live migrate of VIF with mac %(mac)s."
msgstr "Ein Rollback der Livemigration des VIF mit der MAC-Adresse %(mac)s wird durchgeführt."

#: nova_powervm/virt/powervm/vif.py:857
#, python-format
msgid "Deleting target side trunk adapter %(dev)s for rollback operation"
msgstr "Der Trunkadapter %(dev)s auf der Zielseite wird für die Rollback-Operation gelöscht."

#: nova_powervm/virt/powervm/disk/driver.py:225
#, python-format
msgid ""
"Failed to map boot disk %(disk_name)s of instance %(instance_name)s to the "
"management partition from Virtual I/O Server %(vios_name)s: %(exc)s"
msgstr ""
"Fehler beim Zuordnen des Bootdatenträgers %(disk_name)s der Instanz %(instance_name)s zur "
"Managementpartition des virtuellen E/A-Servers %(vios_name)s: %(exc)s"

#: nova_powervm/virt/powervm/disk/driver.py:354
#, python-format
msgid ""
"Instance %(inst)s Disk Upload attempt #%(attempt)d failed. Retrying the "
"upload."
msgstr ""
"Instanz %(inst)s Versuchter Datenträger-Upload %(attempt)d ist fehlgeschlagen. Upload "
"wird wiederholt."

#: nova_powervm/virt/powervm/nvram/manager.py:127
#, python-format
msgid "Could not delete NVRAM: %s"
msgstr "Der nicht flüchtige Arbeitsspeicher konnte nicht gelöscht werden: %s"

#: nova_powervm/virt/powervm/nvram/manager.py:198
#, python-format
msgid "Unable to store the NVRAM for instance: %s"
msgstr "Der nicht flüchtige Arbeitsspeicher für die Instanz: %s kann nicht gespeichert werden"

#: nova_powervm/virt/powervm/nvram/swift.py:182
msgid "NVRAM upload failed due to invalid token. Retrying upload."
msgstr "NVRAM-Upload ist aufgrund eines ungültigen Tokens fehlgeschlagen. Upload wird wiederholt."

#: nova_powervm/virt/powervm/nvram/swift.py:288
#, python-format
msgid "Could not remove temporary file: %s"
msgstr "Die temporäre Datei: %s konnte nicht entfernt werden"

#: nova_powervm/virt/powervm/tasks/base.py:63
#, python-format
msgid "Reverting task %(task)s for instance %(inst)s"
msgstr "Zurücksetzen der Task %(task)s für Instanz %(inst)s"

#: nova_powervm/virt/powervm/tasks/base.py:71
#, python-format
msgid ""
"Revert task %(task)s completed in %(seconds)d seconds for instance %(inst)s"
msgstr ""
"Zurücksetzen der Task %(task)s in %(seconds)d für Instanz %(inst)s abgeschlossen"

#: nova_powervm/virt/powervm/tasks/network.py:169
#, python-format
msgid "Instance was not assigned to this host. It was assigned to: %s"
msgstr "Instanz wurde nicht diesem Host zugewiesen. Wurde zugewiesen zu: %s"

#: nova_powervm/virt/powervm/tasks/network.py:252
#, python-format
msgid "VIF creation being rolled back for instance %(inst)s"
msgstr "VIF-Erstellung wird für Instanz %(inst)s rückgängig gemacht"

#: nova_powervm/virt/powervm/tasks/network.py:264
msgid "An exception occurred during an unplug in the vif rollback.  Ignoring."
msgstr "Bei einer Trennoperation im VIF-Rollback ist eine Ausnahmebedingung aufgetreten. Wird ignoriert."

#: nova_powervm/virt/powervm/tasks/network.py:312
#, python-format
msgid ""
"No management VIF created for instance %s due to lack of Management Virtual "
"Switch"
msgstr ""
"Für Instanz %s wurde kein Management-VIF erstellt, da ein virtueller "
"Managementswitch fehlte."

#: nova_powervm/virt/powervm/tasks/storage.py:62
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be disconnected"
msgstr "Zu trennender Datenträger %(vol)s für Instanz %(inst)s"

#: nova_powervm/virt/powervm/tasks/storage.py:78
#, python-format
msgid ""
"Unable to disconnect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Der Datenträger %(inst)s konnte während des Rollbacks nicht getrennt werden. Folgender Fehler wurde gemeldet: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:110
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be re-connected"
msgstr "Datenträger %(vol)s für Instanz %(inst)s, zu dem die Verbindung wiederhergestellt werden soll"

#: nova_powervm/virt/powervm/tasks/storage.py:127
#, python-format
msgid ""
"Unable to re-connect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Die Verbindung zum Datenträger %(inst)s konnte während des Rollbacks nicht wiederhergestellt werden. Folgender Fehler wurde gemeldet: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:284
#, python-format
msgid ""
"Unmapping boot disk %(disk_name)s of instance %(instance_name)s from "
"management partition via Virtual I/O Server %(vios_name)s."
msgstr ""
"Die Zuordnung des Bootdatenträgers %(disk_name)s der Instanz %(instance_name)s in der "
"Managementpartition wird über den virtuellen E/A-Server %(vios_name)s aufgehoben."

#: nova_powervm/virt/powervm/tasks/storage.py:296
#, python-format
msgid "Removing disk %(disk_path)s from the management partition."
msgstr "Die Platte %(disk_path)s wird von der Managementpartition entfernt."

#: nova_powervm/virt/powervm/tasks/storage.py:407
#, python-format
msgid "Vopt removal as part of spawn reversion failed with: %(exc)s"
msgstr "Entfernen der virtuellen optischen Einheit im Zuge einer Startzurücksetzung ist fehlgeschlagen: %(exc)s"

#: nova_powervm/virt/powervm/tasks/storage.py:545
#, python-format
msgid "Disk not found: %(disk_name)s"
msgstr "Platte nicht gefunden: %(disk_name)s"

#: nova_powervm/virt/powervm/tasks/vm.py:226
#, python-format
msgid "Powering off instance: %s"
msgstr "Instanz %s wird ausgeschaltet."

#: nova_powervm/virt/powervm/volume/iscsi.py:153
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual I/O "
"Server %(vios)s is not in a valid state.  No disconnect actions to be taken "
"as volume is not healthy."
msgstr ""
"Datenträger trennen: Die Sicherungs-HDisk für den Datenträger %(volume_id)s auf dem virtuellen "
"E/A-Server %(vios)s befindet sich in einem nicht gültigen Zustand. Es sind keine Aktionen zur Trennung der Verbindung "
"zu unternehmen, weil der Datenträger nicht in einwandfreiem Zustand ist."

#: nova_powervm/virt/powervm/volume/iscsi.py:163
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server %(vios_name)s "
"for volume %(volume_id)s. Error: %(error)s"
msgstr ""
"Datenträger trennen: Es wurde keine Platte auf dem virtuellen E/A-Server %(vios_name)s "
"für Datenträger %(volume_id)s gefunden. Fehler: %(error)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:206
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the  volume %(volume_id)s on ANY of "
"the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Datenträger trennen: Die Trennung des Datenträgers %(volume_id)s ist auf ALLEN "
"virtuellen E/A-Servern für Instanz %(inst)s fehlgeschlagen."

#: nova_powervm/virt/powervm/volume/npiv.py:490
#, python-format
msgid ""
"Had to update the system metadata for the WWPNs due to incorrect physical "
"WWPNs on fabric %(fabric)s"
msgstr ""
"Es mussten die Systemmetadaten für die WWPNs wegen falscher physischer"
" WWPNs auf Fabric %(fabric)s aktualisiert werden"

#: nova_powervm/virt/powervm/volume/npiv.py:590
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC Fabric "
"%(fabric)s."
msgstr ""
"Es wurden keine Speicherverbindungen gefunden zwischen den virtuellen E/A-Servern und FC-Fabric "
"%(fabric)s."

#: nova_powervm/virt/powervm/volume/npiv.py:703
#, python-format
msgid ""
"No NPIV mappings exist for instance %(inst)s on fabric %(fabric)s.  May not "
"have connected to the fabric yet or fabric configuration was recently "
"modified."
msgstr ""
"Es sind keine NPIV-Zuordnungen für Instanz %(inst)s in Fabric %(fabric)s vorhanden. Möglicherweise "
"wurden sie noch nicht mit dem Fabric verbunden oder die Fabric-Konfiguration wurde vor kurzem "
"modifiziert."

#: nova_powervm/virt/powervm/volume/volume.py:242
#, python-format
msgid ""
"There was an error removing the hdisk %(disk)s from the Virtual I/O Server."
msgstr ""
"Beim Entfernen der HDisk %(disk)s vom virtuellen E/A-Server ist ein Fehler aufgetreten."

#: nova_powervm/virt/powervm/volume/volume.py:282
#, python-format
msgid "Could not remove hdisk for volume: %s"
msgstr "Die HDisk für den Datenträger: %s konnte nicht entfernt werden"

#: nova_powervm/virt/powervm/volume/vscsi.py:197
#, python-format
msgid ""
"Discovered device %(dev)s for volume %(volume)s on %(vios)s is in use. Error "
"code: %(status)s."
msgstr ""
"Die erkannte Einheit %(dev)s für Datenträger %(volume)s auf %(vios)s wird bereits verwendet. Fehler"
"%(status)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:278
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual I/O "
"Server %(vios)s is not in a valid state.  This may be the result of an "
"evacuate."
msgstr ""
"Datenträger trennen: Die Sicherungs-HDisk für den Datenträger %(volume_id)s auf dem virtuellen "
"E/A-Server %(vios)s befindet sich in einem nicht gültigen Zustand. Dies könnte das Ergebnis "
"einer Auslagerung sein."

#: nova_powervm/virt/powervm/volume/vscsi.py:288
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server %(vios_name)s "
"for volume %(volume_id)s. Volume UDID: %(volume_uid)s.  Error: %(error)s"
msgstr ""
"Datenträger trennen: Es wurde keine Platte auf dem virtuellen E/A-Server %(vios_name)s "
"für Datenträger %(volume_id)s gefunden. Datenträger-UDID: %(volume_uid)s. Fehler: %(error)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:330
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the volume %(volume_id)s on ANY of "
"the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Datenträger trennen: Die Trennung des Datenträgers %(volume_id)s ist auf ALLEN "
"virtuellen E/A-Servern für Instanz %(inst)s fehlgeschlagen."

# ENGL1SH_VERS10N 12659_13 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 49
# T9N_SH1P_STR1NG PV133AAP001 2
