# Translations template for nova_powervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 4.0.1.dev5\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:07-0400\n"
"PO-Revision-Date: 2017-04-20 10:07-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: nova_powervm/virt/powervm/driver.py:624
#, python-format
msgid ""
"Removing %(num_maps)d storage-less VSCSI mappings associated with LPAR ID "
"%(lpar_uuid)s from VIOS %(vios_name)s."
msgstr ""
"正从 VIOS %(vios_name)s 移除与 LPAR 标识 %(lpar_uuid)s 相关联的 %(num_maps)d 个"
"无存储器 VSCSI 映射。"

#: nova_powervm/virt/powervm/driver.py:664
#: nova_powervm/virt/powervm/driver.py:674
msgid "VM was not found during destroy operation."
msgstr "破坏操作期间找不到 VM。"

#: nova_powervm/virt/powervm/driver.py:1075
msgid ""
"VM was not found during unplug operation as it is already possibly deleted"
msgstr ""
"拔出操作期间未发现 VM，因为可能已将其删除"

#: nova_powervm/virt/powervm/driver.py:1102
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: %(ifaces)s"
msgstr ""
"在任何接口 %(ifaces)s 上都找不到 my_ip 地址 (%(my_ip)s)"

#: nova_powervm/virt/powervm/driver.py:1571
msgid "Rolling back live migration."
msgstr "正在回滚实时迁移。"

#: nova_powervm/virt/powervm/event.py:121
#, python-format
msgid "Unable to parse event URI: %s from PowerVM."
msgstr "无法从 PowerVM 解析事件 URI %s。"

#: nova_powervm/virt/powervm/host.py:204
#, python-format
msgid ""
"Host CPU Metrics determined that the total cycles reported was less than the "
"used cycles.  This indicates an issue with the PCM data.  Please investigate "
"the results.\n"
"Total Delta Cycles: %(tot_cycles)d\n"
"User Delta Cycles: %(user_cycles)d\n"
"Firmware Delta Cycles: %(fw_cycles)d"
msgstr ""
"主机 CPU 指标确定所报告的周期总数小于"
"已使用周期数。这指示 PCM 数据存在问题。请调查"
"结果。\n"
"增量周期总数：%(tot_cycles)d\n"
"用户增量周期数：%(user_cycles)d\n"
"固件增量周期数：%(fw_cycles)d"

#: nova_powervm/virt/powervm/slot.py:180
#, python-format
msgid ""
"Unable to delete the slot map from Swift backing store with ID %(key)s.  "
"Will require manual cleanup."
msgstr ""
"无法从标识为 %(key)s 的 Swift 后备存储器删除插槽映射。"
"将需要手动清除。"

#: nova_powervm/virt/powervm/vif.py:357 nova_powervm/virt/powervm/vif.py:588
#: nova_powervm/virt/powervm/vif.py:758
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  The VIF was "
"not found on the instance."
msgstr ""
"无法对实例 %(inst)s 拔出 MAC 为 %(mac)s 的 VIF。在"
"该实例上找不到该 VIF。"

#: nova_powervm/virt/powervm/vif.py:604
#, python-format
msgid ""
"Unable to delete device %(dev_name)s from bridge %(bridge)s. Error: %(error)s"
msgstr ""
"无法从网桥 %(bridge)s 删除设备 %(dev_name)s。错误：%(error)s"

#: nova_powervm/virt/powervm/vif.py:685
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  No matching "
"vNIC was found on the instance.  VIF: %(vif)s"
msgstr ""
"无法对实例 %(inst)s 拔出 MAC 为 %(mac)s 的 VIF。在"
"在实例中找到了 vNIC。VIF：%(vif)s"

#: nova_powervm/virt/powervm/vif.py:827
#, python-format
msgid "Rolling back the live migrate of VIF with mac %(mac)s."
msgstr "正在回滚具有 Mac %(mac)s 的 VIF 的实时迁移。"

#: nova_powervm/virt/powervm/vif.py:857
#, python-format
msgid "Deleting target side trunk adapter %(dev)s for rollback operation"
msgstr "正在删除目标端干线适配器 %(dev)s 以执行回滚操作"

#: nova_powervm/virt/powervm/disk/driver.py:225
#, python-format
msgid ""
"Failed to map boot disk %(disk_name)s of instance %(instance_name)s to the "
"management partition from Virtual I/O Server %(vios_name)s: %(exc)s"
msgstr ""
"无法将实例 %(instance_name)s 的引导磁盘 %(disk_name)s 映射至"
"Virtual I/O Server %(vios_name)s 中的管理分区：%(exc)s"

#: nova_powervm/virt/powervm/disk/driver.py:354
#, python-format
msgid ""
"Instance %(inst)s Disk Upload attempt #%(attempt)d failed. Retrying the "
"upload."
msgstr ""
"实例 %(inst)s 磁盘上载尝试 %(attempt)d 失败。"
"正在重试上载。"

#: nova_powervm/virt/powervm/nvram/manager.py:127
#, python-format
msgid "Could not delete NVRAM: %s"
msgstr "无法删除 NVRAM：%s"

#: nova_powervm/virt/powervm/nvram/manager.py:198
#, python-format
msgid "Unable to store the NVRAM for instance: %s"
msgstr "无法存储实例的 NVRAM：%s"

#: nova_powervm/virt/powervm/nvram/swift.py:182
msgid "NVRAM upload failed due to invalid token. Retrying upload."
msgstr "由于无效令牌而导致 NVRAM 上载失败。正在重试上载。"

#: nova_powervm/virt/powervm/nvram/swift.py:288
#, python-format
msgid "Could not remove temporary file: %s"
msgstr "无法移除临时文件：%s"

#: nova_powervm/virt/powervm/tasks/base.py:63
#, python-format
msgid "Reverting task %(task)s for instance %(inst)s"
msgstr "正对实例 %(inst)s 还原任务 %(task)s"

#: nova_powervm/virt/powervm/tasks/base.py:71
#, python-format
msgid ""
"Revert task %(task)s completed in %(seconds)d seconds for instance %(inst)s"
msgstr ""
"针对实例 %(inst)s 的还原任务 %(task)s 在 %(seconds)d 秒内完成"

#: nova_powervm/virt/powervm/tasks/network.py:169
#, python-format
msgid "Instance was not assigned to this host. It was assigned to: %s"
msgstr "未对此主机分配实例。它被分配给：%s"

#: nova_powervm/virt/powervm/tasks/network.py:252
#, python-format
msgid "VIF creation being rolled back for instance %(inst)s"
msgstr "正对实例 %(inst)s 回滚 VIF 创建"

#: nova_powervm/virt/powervm/tasks/network.py:264
msgid "An exception occurred during an unplug in the vif rollback.  Ignoring."
msgstr "在 VIF 回滚中拔掉插头时发生了异常。正在忽略。"

#: nova_powervm/virt/powervm/tasks/network.py:312
#, python-format
msgid ""
"No management VIF created for instance %s due to lack of Management Virtual "
"Switch"
msgstr ""
"由于缺少管理虚拟机而未对实例 %s"
"创建管理 VIF"

#: nova_powervm/virt/powervm/tasks/storage.py:62
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be disconnected"
msgstr "实例 %(inst)s 的卷 %(vol)s 待断开连接"

#: nova_powervm/virt/powervm/tasks/storage.py:78
#, python-format
msgid ""
"Unable to disconnect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"回滚期间，无法为 %(inst)s 的卷断开连接。错误为："
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:110
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be re-connected"
msgstr "实例 %(inst)s 的卷 %(vol)s 待重新连接"

#: nova_powervm/virt/powervm/tasks/storage.py:127
#, python-format
msgid ""
"Unable to re-connect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"回滚期间，无法为 %(inst)s 的卷重新连接。错误为："
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:284
#, python-format
msgid ""
"Unmapping boot disk %(disk_name)s of instance %(instance_name)s from "
"management partition via Virtual I/O Server %(vios_name)s."
msgstr ""
"已通过 Virtual I/O Server %(vios_name)s 从管理分区取消实例 %(instance_name)s 的"
"引导磁盘 %(disk_name)s 的映射。"

#: nova_powervm/virt/powervm/tasks/storage.py:296
#, python-format
msgid "Removing disk %(disk_path)s from the management partition."
msgstr "正在从管理分区除去磁盘 %(disk_path)s。"

#: nova_powervm/virt/powervm/tasks/storage.py:407
#, python-format
msgid "Vopt removal as part of spawn reversion failed with: %(exc)s"
msgstr "作为衍生逆转的一部分的移除 Vopt 失败：%(exc)s"

#: nova_powervm/virt/powervm/tasks/storage.py:545
#, python-format
msgid "Disk not found: %(disk_name)s"
msgstr "找不到磁盘：%(disk_name)s"

#: nova_powervm/virt/powervm/tasks/vm.py:226
#, python-format
msgid "Powering off instance: %s"
msgstr "正在关闭实例 %s"

#: nova_powervm/virt/powervm/volume/iscsi.py:153
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual I/O "
"Server %(vios)s is not in a valid state.  No disconnect actions to be taken "
"as volume is not healthy."
msgstr ""
"对卷断开连接：卷 %(volume_id)s（位于 Virtual I/O "
"Server %(vios)s 上）未处于有效状态。这可能是撤出造成的结果。"
"因为卷处于非正常状态。"

#: nova_powervm/virt/powervm/volume/iscsi.py:163
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server %(vios_name)s "
"for volume %(volume_id)s. Error: %(error)s"
msgstr ""
"对卷断开连接：在 Virtual I/O Server %(vios_name)s 上找不到对应"
"卷 %(volume_id)s 的磁盘。错误：%(error)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:206
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the  volume %(volume_id)s on ANY of "
"the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"对卷断开连接：对于实例 %(inst)s，未能在任何 Virtual I/O Server 上对卷 %(volume_id)s"
"断开连接。"

#: nova_powervm/virt/powervm/volume/npiv.py:490
#, python-format
msgid ""
"Had to update the system metadata for the WWPNs due to incorrect physical "
"WWPNs on fabric %(fabric)s"
msgstr ""
"必须更新 WWPN 的系统元数据，因为"
"光纤网 %(fabric)s 上存在不正确的物理 WWPN"

#: nova_powervm/virt/powervm/volume/npiv.py:590
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC Fabric "
"%(fabric)s."
msgstr ""
"在 Virtual I/O Server 与 FC 光纤网"
"%(fabric)s."

#: nova_powervm/virt/powervm/volume/npiv.py:703
#, python-format
msgid ""
"No NPIV mappings exist for instance %(inst)s on fabric %(fabric)s.  May not "
"have connected to the fabric yet or fabric configuration was recently "
"modified."
msgstr ""
"光纤网 %(fabric)s 上的实例 %(inst)s 没有 NPIV 映射。可能"
"尚未连接至光纤网或光纤网配置最近"
"已修改。"

#: nova_powervm/virt/powervm/volume/volume.py:242
#, python-format
msgid ""
"There was an error removing the hdisk %(disk)s from the Virtual I/O Server."
msgstr ""
"从 Virtual I/O Server 移除 hdisk %(disk)s 时发生错误。"

#: nova_powervm/virt/powervm/volume/volume.py:282
#, python-format
msgid "Could not remove hdisk for volume: %s"
msgstr "无法移除卷的 hdisk：%s"

#: nova_powervm/virt/powervm/volume/vscsi.py:197
#, python-format
msgid ""
"Discovered device %(dev)s for volume %(volume)s on %(vios)s is in use. Error "
"code: %(status)s."
msgstr ""
"发现 %(vios)s 上卷 %(volume)s 的设备 %(dev)s 正在使用中。错误"
"码：%(status)s。"

#: nova_powervm/virt/powervm/volume/vscsi.py:278
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual I/O "
"Server %(vios)s is not in a valid state.  This may be the result of an "
"evacuate."
msgstr ""
"对卷断开连接：卷 %(volume_id)s（位于 Virtual I/O "
"Server %(vios)s 上）未处于有效状态。这可能是撤出"
"造成的结果。"

#: nova_powervm/virt/powervm/volume/vscsi.py:288
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server %(vios_name)s "
"for volume %(volume_id)s. Volume UDID: %(volume_uid)s.  Error: %(error)s"
msgstr ""
"对卷断开连接：在 Virtual I/O Server %(vios_name)s 上找不到对应"
"卷 %(volume_id)s 的磁盘。卷 UDID：%(volume_uid)s。错误：%(error)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:330
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the volume %(volume_id)s on ANY of "
"the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"对卷断开连接：对于实例 %(inst)s，未能在任何 Virtual I/O Server 上对卷 %(volume_id)s"
"断开连接。"

# ENGL1SH_VERS10N 12659_13 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 49
# T9N_SH1P_STR1NG PV133AAP001 2
