# Translations template for nova_powervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 4.0.1.dev5\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:07-0400\n"
"PO-Revision-Date: 2017-04-20 10:07-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: nova_powervm/virt/powervm/driver.py:624
#, python-format
msgid ""
"Removing %(num_maps)d storage-less VSCSI mappings associated with LPAR ID "
"%(lpar_uuid)s from VIOS %(vios_name)s."
msgstr ""
"Удаление %(num_maps)d связей VSCSI без памяти, относящихся к LPAR с ИД "
"%(lpar_uuid)s из VIOS %(vios_name)s."

#: nova_powervm/virt/powervm/driver.py:664
#: nova_powervm/virt/powervm/driver.py:674
msgid "VM was not found during destroy operation."
msgstr "Во время операции уничтожения не найдена ВМ."

#: nova_powervm/virt/powervm/driver.py:1075
msgid ""
"VM was not found during unplug operation as it is already possibly deleted"
msgstr ""
"Виртуальная машина не найдена в ходе операции отключения. Вероятно, она уже удалена"

#: nova_powervm/virt/powervm/driver.py:1102
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: %(ifaces)s"
msgstr ""
"Адрес my_ip (%(my_ip)s) не найден ни в одном из интерфейсов: %(ifaces)s"

#: nova_powervm/virt/powervm/driver.py:1571
msgid "Rolling back live migration."
msgstr "Откат оперативной миграции."

#: nova_powervm/virt/powervm/event.py:121
#, python-format
msgid "Unable to parse event URI: %s from PowerVM."
msgstr "Ошибка анализа URI события: %s из PowerVM."

#: nova_powervm/virt/powervm/host.py:204
#, python-format
msgid ""
"Host CPU Metrics determined that the total cycles reported was less than the "
"used cycles.  This indicates an issue with the PCM data.  Please investigate "
"the results.\n"
"Total Delta Cycles: %(tot_cycles)d\n"
"User Delta Cycles: %(user_cycles)d\n"
"Firmware Delta Cycles: %(fw_cycles)d"
msgstr ""
"Согласно показателям CPU хоста общее количество циклов в отчете меньше, "
"чем число использованных циклов.  Это признак некорректности данных PCM.  Изучите "
"результаты.\n"
"Общее количество циклов: %(tot_cycles)d\n"
"Количество циклов пользователя: %(user_cycles)d\n"
"Количество циклов встроенного ПО: %(fw_cycles)d"

#: nova_powervm/virt/powervm/slot.py:180
#, python-format
msgid ""
"Unable to delete the slot map from Swift backing store with ID %(key)s.  "
"Will require manual cleanup."
msgstr ""
"Не удалось удалить карту разъемов из резервного хранилища Swift с ИД %(key)s.  "
"Потребуется очистка вручную."

#: nova_powervm/virt/powervm/vif.py:357 nova_powervm/virt/powervm/vif.py:588
#: nova_powervm/virt/powervm/vif.py:758
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  The VIF was "
"not found on the instance."
msgstr ""
"Не удалось отсоединить VIF с MAC-адресом %(mac)s для экземпляра %(inst)s.  VIF "
"не найден в экземпляре."

#: nova_powervm/virt/powervm/vif.py:604
#, python-format
msgid ""
"Unable to delete device %(dev_name)s from bridge %(bridge)s. Error: %(error)s"
msgstr ""
"Невозможно удалить устройство %(dev_name)s из моста %(bridge)s. Ошибка: %(error)s"

#: nova_powervm/virt/powervm/vif.py:685
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  No matching "
"vNIC was found on the instance.  VIF: %(vif)s"
msgstr ""
"Не удалось отсоединить VIF с MAC-адресом %(mac)s для экземпляра %(inst)s.  Соответствующие "
"vNIC не найдены в экземпляре.  VIF: %(vif)s"

#: nova_powervm/virt/powervm/vif.py:827
#, python-format
msgid "Rolling back the live migrate of VIF with mac %(mac)s."
msgstr "Выполняется откат оперативной миграции VIF с MAC-адресом %(mac)s."

#: nova_powervm/virt/powervm/vif.py:857
#, python-format
msgid "Deleting target side trunk adapter %(dev)s for rollback operation"
msgstr "Выполняется удаление целевого магистрального адаптера %(dev)s в процессе операции отката"

#: nova_powervm/virt/powervm/disk/driver.py:225
#, python-format
msgid ""
"Failed to map boot disk %(disk_name)s of instance %(instance_name)s to the "
"management partition from Virtual I/O Server %(vios_name)s: %(exc)s"
msgstr ""
"Не удалось подключить загрузочный диск %(disk_name)s экземпляра %(instance_name)s к "
"разделу управления из сервера VIOS %(vios_name)s: %(exc)s"

#: nova_powervm/virt/powervm/disk/driver.py:354
#, python-format
msgid ""
"Instance %(inst)s Disk Upload attempt #%(attempt)d failed. Retrying the "
"upload."
msgstr ""
"%(attempt)d-ая попытка передать диск для экземпляра %(inst)s завершилась неудачно. Будет "
"сделана еще одна попытка передачи."

#: nova_powervm/virt/powervm/nvram/manager.py:127
#, python-format
msgid "Could not delete NVRAM: %s"
msgstr "Не удалось удалить NVRAM: %s"

#: nova_powervm/virt/powervm/nvram/manager.py:198
#, python-format
msgid "Unable to store the NVRAM for instance: %s"
msgstr "Не удалось сохранить NVRAM для экземпляра: %s"

#: nova_powervm/virt/powervm/nvram/swift.py:182
msgid "NVRAM upload failed due to invalid token. Retrying upload."
msgstr "Передача NVRAM не выполнена из-за недопустимого маркера. Будет сделана еще одна попытка передачи."

#: nova_powervm/virt/powervm/nvram/swift.py:288
#, python-format
msgid "Could not remove temporary file: %s"
msgstr "Не удалось удалить временный файл: %s"

#: nova_powervm/virt/powervm/tasks/base.py:63
#, python-format
msgid "Reverting task %(task)s for instance %(inst)s"
msgstr "Возврат задачи %(task)s для экземпляра %(inst)s"

#: nova_powervm/virt/powervm/tasks/base.py:71
#, python-format
msgid ""
"Revert task %(task)s completed in %(seconds)d seconds for instance %(inst)s"
msgstr ""
"Отмена задачи %(task)s выполнена за %(seconds)d с. для экземпляра %(inst)s"

#: nova_powervm/virt/powervm/tasks/network.py:169
#, python-format
msgid "Instance was not assigned to this host. It was assigned to: %s"
msgstr "Экземпляр не присвоен этому хосту. Он присвоен хосту %s"

#: nova_powervm/virt/powervm/tasks/network.py:252
#, python-format
msgid "VIF creation being rolled back for instance %(inst)s"
msgstr "Откат создания VIF для экземпляра %(inst)s"

#: nova_powervm/virt/powervm/tasks/network.py:264
msgid "An exception occurred during an unplug in the vif rollback.  Ignoring."
msgstr "Возникла исключительная ситуация при отключении в откате VIF. Она проигнорирована."

#: nova_powervm/virt/powervm/tasks/network.py:312
#, python-format
msgid ""
"No management VIF created for instance %s due to lack of Management Virtual "
"Switch"
msgstr ""
"Для экземпляра %s не создан VIF управления, так как отсутствует виртуальный "
"коммутатор управления"

#: nova_powervm/virt/powervm/tasks/storage.py:62
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be disconnected"
msgstr "Планируется отключение тома %(vol)s для экземпляра %(inst)s"

#: nova_powervm/virt/powervm/tasks/storage.py:78
#, python-format
msgid ""
"Unable to disconnect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Не удалось отключить том для %(inst)s в процессе отката. Ошибка: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:110
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be re-connected"
msgstr "Планируется повторное подключение тома %(vol)s для экземпляра %(inst)s"

#: nova_powervm/virt/powervm/tasks/storage.py:127
#, python-format
msgid ""
"Unable to re-connect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Не удалось повторно подключить том для %(inst)s в процессе отката. Ошибка: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:284
#, python-format
msgid ""
"Unmapping boot disk %(disk_name)s of instance %(instance_name)s from "
"management partition via Virtual I/O Server %(vios_name)s."
msgstr ""
"Удаление связи загрузочного диска %(disk_name)s экземпляра %(instance_name)s из "
"раздела управления через виртуальный сервер ввода-вывода %(vios_name)s."

#: nova_powervm/virt/powervm/tasks/storage.py:296
#, python-format
msgid "Removing disk %(disk_path)s from the management partition."
msgstr "Удаление %(disk_path)s диска из раздела управления."

#: nova_powervm/virt/powervm/tasks/storage.py:407
#, python-format
msgid "Vopt removal as part of spawn reversion failed with: %(exc)s"
msgstr "Сбой удаления Vopt в ходе отката операции создания. Ошибка: %(exc)s"

#: nova_powervm/virt/powervm/tasks/storage.py:545
#, python-format
msgid "Disk not found: %(disk_name)s"
msgstr "Диск не найден: %(disk_name)s"

#: nova_powervm/virt/powervm/tasks/vm.py:226
#, python-format
msgid "Powering off instance: %s"
msgstr "Выключение экземпляра: %s"

#: nova_powervm/virt/powervm/volume/iscsi.py:153
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual I/O "
"Server %(vios)s is not in a valid state.  No disconnect actions to be taken "
"as volume is not healthy."
msgstr ""
"Отключение тома: базовый жесткий диск тома %(volume_id)s из сервера VIOS "
"%(vios)s не находится в корректном состоянии.  Никакие операции отключения не допустимы, "
"так как том неисправен."

#: nova_powervm/virt/powervm/volume/iscsi.py:163
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server %(vios_name)s "
"for volume %(volume_id)s. Error: %(error)s"
msgstr ""
"Отключение тома: не удалось найти диск на сервере VIOS %(vios_name)s "
"для тома %(volume_id)s. Ошибка: %(error)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:206
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the  volume %(volume_id)s on ANY of "
"the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Отключение тома: не удалось отключить том %(volume_id)s ни на одном из "
"серверов VIOS для экземпляра %(inst)s."

#: nova_powervm/virt/powervm/volume/npiv.py:490
#, python-format
msgid ""
"Had to update the system metadata for the WWPNs due to incorrect physical "
"WWPNs on fabric %(fabric)s"
msgstr ""
"Потребовалось обновить метаданные системы для WWPN из-за неверных физических "
"WWPN в фабрике %(fabric)s"

#: nova_powervm/virt/powervm/volume/npiv.py:590
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC Fabric "
"%(fabric)s."
msgstr ""
"Не найдены соединения системы хранения, связывающие серверы VIOS и фабрику FC "
"%(fabric)s."

#: nova_powervm/virt/powervm/volume/npiv.py:703
#, python-format
msgid ""
"No NPIV mappings exist for instance %(inst)s on fabric %(fabric)s.  May not "
"have connected to the fabric yet or fabric configuration was recently "
"modified."
msgstr ""
"Нет ни одной связи NPIV для экземпляра %(inst)s в фабрике %(fabric)s.  Он еще "
"не подключен к фабрике, либо конфигурация фабрики недавно "
"изменялась."

#: nova_powervm/virt/powervm/volume/volume.py:242
#, python-format
msgid ""
"There was an error removing the hdisk %(disk)s from the Virtual I/O Server."
msgstr ""
"Возникла ошибка при удалении жесткого диска %(disk)s с сервера VIOS."

#: nova_powervm/virt/powervm/volume/volume.py:282
#, python-format
msgid "Could not remove hdisk for volume: %s"
msgstr "Не удалось удалить жесткий диск для тома %s"

#: nova_powervm/virt/powervm/volume/vscsi.py:197
#, python-format
msgid ""
"Discovered device %(dev)s for volume %(volume)s on %(vios)s is in use. Error "
"code: %(status)s."
msgstr ""
"Обнаруженное устройство %(dev)s для тома %(volume)s на сервере %(vios)s занято. Ошибка "
"состояния: %(status)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:278
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual I/O "
"Server %(vios)s is not in a valid state.  This may be the result of an "
"evacuate."
msgstr ""
"Отключение тома: базовый жесткий диск тома %(volume_id)s из сервера VIOS "
"%(vios)s не находится в корректном состоянии.  Это может быть результатом "
"освобождения."

#: nova_powervm/virt/powervm/volume/vscsi.py:288
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server %(vios_name)s "
"for volume %(volume_id)s. Volume UDID: %(volume_uid)s.  Error: %(error)s"
msgstr ""
"Отключение тома: не удалось найти диск на сервере VIOS %(vios_name)s "
"для тома %(volume_id)s. UDID тома: %(volume_uid)s.  Ошибка: %(error)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:330
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the volume %(volume_id)s on ANY of "
"the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Отключение тома: не удалось отключить том %(volume_id)s ни на одном из "
"серверов VIOS для экземпляра %(inst)s."

# ENGL1SH_VERS10N 12659_13 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 49
# T9N_SH1P_STR1NG PV133AAP001 2
